./RTL/encoder_3b4b.sv
./RTL/encoder_5b6b.sv
./RTL/encoder_8b10b.sv
./RTL/decoder_4b3b.sv
./RTL/decoder_6b5b.sv
./RTL/decoder_10b8b.sv
./RTL/Deserializer_fsm.sv
./RTL/deserializer_counter.sv
./RTL/Deserializer_CTL.sv
./RTL/Serializer_fsm.sv
./RTL/Serializer_counter.sv
./RTL/Serializer_CTL.sv
./RTL/PISO.sv
./RTL/SIPO.sv
./RTL/CTL.sv
./RTL/Deserializer.sv
./RTL/Serializer.sv
./RTL/SerDes.sv
./RTL/Duplex_Top.sv
